# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bba5501eacb47414172da68d0f1eee260c5444c5acd105394892e138bc7494137c3ca9944cc45efc61a9bcc4a955c595feba20bba6d833dab741a993277264e8

test:
  secret_key_base: 08dc785b78cfa245b70645a3f4785d7c1a80f56d27b703cacc4b5a29a0f457bc10b3faa6a76b4dc6985d4cc1857fa570f46bfffc1b57e954ab893659b94debd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
